# Generated by Django 5.1.7 on 2025-04-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_expenditure_product_alter_users_email_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='revenue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
